on:
  workflow_dispatch:
  # Disabled for now because it's not ready yet
  # push:
  #   branches:
  #     - main # trigger whenever there's a commit on this

jobs:
  main-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./observatoire_website
    steps:
      - uses: actions/checkout@v4
      # login into docker hub
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build and push
      - uses: docker/build-push-action@v5
        with:
          # needed to go into the subdirectory
          context: observatoire_website
          push: true
          tags: implicitdef/anticor_observatoire:latest
